// const Images = {
// 	twitter: require("../images/twitter.svg").default.src,
// 	forward_arrow: require("../images/svgs/forward-arrow.svg").default.src,
// 	delete: require("../images/svgs/delete_FILL0_wght400_GRAD0_opsz48.svg")
// 		.default.src,
// 	default_thumbnail: require("../images/svgs/default_thumbnail.svg").default
// 		.src,
// 	stars: require("../images/svgs/stars.svg").default.src,
// 	facebook: require("../images/facebook.svg").default.src,
// 	facebook_2: require("../images/facebook_2.svg").default.src,
// 	google: require("../images/google.svg").default.src,
// 	instagram: require("../images/instagram.svg").default.src,
// 	sun: require("../images/sun.svg").default.src,
// 	moon: require("../images/moon.svg").default.src,
// 	focus: require("../images/focus.svg").default.src,
// 	easy: require("../images/easy.svg").default.src,

// 	industry: require("../images/industry.svg").default.src,
// 	close: require("../images/close.svg").default.src,
// 	int: require("../images/ints.svg").default.src,
// 	Experience: require("../images/experience.svg").default.src,
// 	School: require("../images/school.svg").default.src,
// 	PostsSvg: require("../images/posts.svg").default.src,
// 	JobSvg: require("../images/jobs.svg").default.src,
// 	pending: require("../images/pending.svg").default.src,
// 	Clients: require("../images/businesssvg.svg").default.src,
// 	Users: require("../images/userssvg.svg").default.src,
// 	OptionDots: require("../images/option.svg").default.src,
// 	Logo: require("../images/premium.svg").default.src,
// 	Cards: require("../images/cards.svg").default.src,
// 	email: require("../images/email.svg").default.src,

//   // Import Images here and svgs above...
//   laptop: require("../images/mockup.png").default.src,
//   normalavatar: require("../images/2Davatar.png").default.src,
//   D1: require("../images/2D1.png").default.src,
//   D2: require("../images/2d2.png").default.src,
//   Bio2: require("../images/bio2.png").default.src,
//   Bio3: require("../images/bio3.png").default.src,
//   AvatarImg: require("../images/avatarimg.png").default.src,
//   // D2: require("../images/2D12.png").default.src,
//   D3: require("../images/2D3.png").default.src,
//   Advert: require("./ad_name.png").default.src,
//   avatarM: require("./avatarM.png").default.src,
//   avatarF: require("./avatarF.png").default.src,
// 	// Import Images here and svgs above...
// 	laptop: require("../images/mockup.png").default.src,
// 	normalavatar: require("../images/2Davatar.png").default.src,
// 	D1: require("../images/2D1.png").default.src,
// 	D2: require("../images/2d2.png").default.src,
// 	Bio2: require("../images/bio2.png").default.src,
// 	Bio3: require("../images/bio3.png").default.src,
// 	// D2: require("../images/2D12.png").default.src,
// 	D3: require("../images/2D3.png").default.src,
// 	Advert: require("./ad_name.png").default.src,

// 	// D4: require("../images/2D4.png").default.src,
// 	medal: require("../images/medal.png").default.src,
// 	AssitantBot: require("../images/AssistantBot.png").default.src,
// 	ReadBlog: require("../images/ReadBlog.png").default.src,
// 	saveto: require("../images/collection.png").default.src,
// 	DummyP: require("../images/aso_oke.jpg").default.src,
// 	Dashboard: require("../images/target.png").default.src,
// 	user1: require("../images/user1.png").default.src,

// 	smile: require("../images/pic1.png").default.src,
// 	suit1: require("../images/suit-1.png").default.src,
// 	suit2: require("../images/suit-2.png").default.src,
// 	YouFirst: require("../images/pic2.png").default.src,
// 	CameraLens: require("../images/pic3.png").default.src,
// 	ariga: require("../images/ariga.png").default.src,
// 	mobnia: require("../images/mobnia.png").default.src,
// 	fundall: require("../images/fundall.png").default.src,
// 	flutterwave: require("../images/flutter.png").default.src,
// 	techpoint: require("../images/techpoint.png").default.src,
// 	support: require("../images/support.png").default.src,
// 	Group: require("../images/together.jpg").default.src,
// 	Grid: require("../images/grid.png").default.src,
// 	star1: require("../images/star1.png").default.src,
// 	woods: require("../images/woods.jpg").default.src,
// 	Profile: require("../images/profile_picture.png").default.src,
// 	G_ig: require("../images/g_ig.png").default.src,
// 	G_fb: require("../images/f_fb.png").default.src,
// 	G_world: require("../images/-g_universe.png").default.src,
// 	potrait: require("../images/dummy_Profile.png").default.src,
// 	universe: require("../images/everywhere.png").default.src,
// 	custom: require("../images/custom.png").default.src,
// 	loading: require("../images/loader.gif").default.src,
// };
// export default Images;
